### ISSUE TITLE
Error run

### ISSUE THREAD

**Issue by pavlo888** [idolawoye/BAGEP#1]
Dear Sir/Madam, 

I have tried to run the package but unfortunately it does not work. I ran the following command: 

(bagep) sam@BioInf2:~/Downloads/BAGEP$ snakemake --config ref=/home/sam/Downloads/BAGEP/Ref-GCF_002005205.3_ASM200520v3_genomic.fna.gz

Then obtained the following error message: 
Building DAG of jobs...
MissingInputException in line 76 of /home/sam/Downloads/BAGEP/Snakefile:
Missing input files for rule vcf_viewer:
core.vcf

Could you please help me solve this issue? 

Thank you in advance for your support. 

Best regards, 
Pablo

**Comment by idolawoye** [comment]
Hi Pablo,

Sorry for the late response (I didn't get a notification on the Issue you raised). Unfortunately, I cannot recreate your error message. Did you install all the dependencies correctly? Also, check that your input FASTQ files are in the correct name format too.
Let me know if you are still getting the same error message
