### ISSUE TITLE
vfc filtered files are empty [Error: fai_fetch failed]

### ISSUE THREAD

**Issue by Hphilippon** [idolawoye/BAGEP#2]
Hi,

I've tried to use your BAGEP pipeline on the dataset available here (https://zenodo.org/record/3731118#.X8jjYOhKg2w).
So I downloaded all the fastq (and I put them in a `$WorkDir/fastq/` folder), the reference genome ( `$WorkDir/ct18genome.fasta`) and I launch your pipeline using:

`snakemake --snakefile $HOME/Software/BAGEP/Snakefile  --config ref=ct18genome.fasta` 

But I got the following error:

```
[15:15:41] Running: bcftools view --include 'FMT/GT="1/1" && QUAL>=100 && FMT/DP>=10 && (FMT/AO)/(FMT/DP)>=0' snps.raw.vcf  | vt normalize -r reference/ref.fa - | bcftools annotate --remove '^INFO/TYPE,^INFO/DP,^INFO/RO,^INFO/AO,^INFO/AB,^FORMAT/GT,^FORMAT/DP,^FORMAT/RO,^FORMAT/AO,^FORMAT/QR,^FORMAT/QA,^FORMAT/GL' > snps.filt.vcf 2>> snps.log
normalize v0.5

options:     input VCF file                                  -
         [o] output VCF file                                 -
         [w] sorting window size                             10000
         [n] no fail on reference inconsistency for non SNPs false
         [q] quiet                                           false
         [d] debug                                           false
         [r] reference FASTA file                            reference/ref.fa

[fai_fetch_seq] Error: fai_fetch failed. (Seeking in a compressed, .gzi unindexed, file?)
[variant_manip.cpp:67 is_ref_consistent] failure to extract base from fasta file: NC_003198.1:8527-8530
```

I think that it's because the SNP is 3 bases long (I used the `-d` option of ` vt normalize` ):

```
NC_003198.1:8680:T/C
NC_003198.1:8732:A/G
NC_003198.1:8737:T/C
NC_003198.1:8743:C/T
NC_003198.1:8750:CTG/TTA
[fai_fetch_seq] Error: fai_fetch failed. (Seeking in a compressed, .gzi unindexed, file?)
[variant_manip.cpp:67 is_ref_consistent] failure to extract base from fasta file: NC_003198.1:8749-8751
```

Can you help me please to resolve this issue ?

Thanks a lot,

Best regards,

Heloise

**Comment by idolawoye** [comment]
Hi Heloise,

Apologies for the late response, I do not receive github notification via email. Unfortunately, I couldn't reproduce the error using the same data set. Please, can you point me directly to what the issue is? Many thanks
