### ISSUE TITLE
How to run BAGEP in conda environment?

### ISSUE THREAD

**Issue by govind-sah** [idolawoye/BAGEP#6]
Hi,

I am trying to analyze Pseudomonas aeruginosa genomes using BAGEP. For this, I followed the steps for `Installation` from the [BAGEP github page](https://github.com/idolawoye/BAGEP/blob/master/README.md) and also setup `Centrifuge` and `Krona Taxonomy Plot`, but now I do not see the command to run the program.
I also do not see any example that illustrates how to use raw .fastq files to generate the results as shown.
It says,
To run the pipeline, simply enter:
`snakemake --config ref={users reference genome}`
Now, I do not get where is the input files and the parameters to run different modules within BAGEP!
Also, what does `users` `reference` and `genome` refers to within the brackets {}?

Please guide me through this.
Thank you,
Govind

**Comment by idolawoye** [comment]
Hi, 

Apologies, I am just seeing this as I did not get a notification earlier.

Your paired-end FASTQ files can be in the same directory you cloned from github or you can simply structure it in a new directory named `fastq`

To run the pipeline, just type `snakemake --config ref={ref_genome}` 

What `{users reference genome}` indicates is the path to where your reference genome is stored, it can be in the `data/` directory

For example: `snakemake --config ref=./data/kleb.fna --cores 4`

**Comment by govind-sah** [comment]
Thank you @idolawoye for your response.
I'll let you know if this works.

**Comment by idolawoye** [comment]
I am closing this issue now that it has been 15 days since your response, Let me know if there is anything I can help with
